### ISSUE TITLE
Routes are not consistent, don't follow conventions

### ISSUE THREAD

**Issue by edalzell** [statamic-rad-pack/shopify#50]
How come it's `/order` but `/product/create` and `/product/update` etc?

Also, I'd recommend making the routes and route names match laravel convention, so `store` not create.

**Comment by jackabox** [comment]
These don't follow conventions due to a few discrepancies between how data is sent from Shopify's webhooks to the system.

It's `/order` as it's not actually doing anything with the order itself (no create, update, etc). It's then using that data to update the products. We aren't creating an order in the system. In theory, we could do this but it wasn't somewhere I wanted to touch so I've left it open at the moment.

It's `/product/update` as there is no way to post to the specific post and do a patch for it. It's always sent as a post, so I've used a generalised tag to catch them all.

Otherwise, these all line up with what Shopify posts them ass. Product - Create, Product - Update.

**Comment by edalzell** [comment]
@ryanmitchell what do you think here?

**Comment by ryanmitchell** [comment]
I’m ok with them as is. Do you feel strongly about it?

**Comment by edalzell** [comment]
Nope
